// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLO5nyS8DpL8P8zYjMDiATmRJtnanF3nA',
    appId: '1:866246340928:web:d28a0d2ad243b6a3034aa5',
    messagingSenderId: '866246340928',
    projectId: 'cv-wala-splitwise',
    authDomain: 'cv-wala-splitwise.firebaseapp.com',
    storageBucket: 'cv-wala-splitwise.appspot.com',
    measurementId: 'G-LFRL9KTM1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfruQkERrhyiVIdJ4rGlTvywIOcAJFIuA',
    appId: '1:866246340928:android:06c717482268fe47034aa5',
    messagingSenderId: '866246340928',
    projectId: 'cv-wala-splitwise',
    storageBucket: 'cv-wala-splitwise.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFzK4KrXhNlvpZl7yYBFRnzYRXMOnSYpE',
    appId: '1:866246340928:ios:867e6d66b49ed76f034aa5',
    messagingSenderId: '866246340928',
    projectId: 'cv-wala-splitwise',
    storageBucket: 'cv-wala-splitwise.appspot.com',
    iosClientId: '866246340928-1b50mbiambg35jri17r9lkbi2gabnuql.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusSplitwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFzK4KrXhNlvpZl7yYBFRnzYRXMOnSYpE',
    appId: '1:866246340928:ios:867e6d66b49ed76f034aa5',
    messagingSenderId: '866246340928',
    projectId: 'cv-wala-splitwise',
    storageBucket: 'cv-wala-splitwise.appspot.com',
    iosClientId: '866246340928-1b50mbiambg35jri17r9lkbi2gabnuql.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusSplitwise',
  );
}
